### ISSUE TITLE
Request url in completion manifest is less useful for POST requests

### ISSUE THREAD

**Issue by gotdan** [HL7/bulk-data#89]
For  POST requests, the url returned as the "request" key in the [completion manifest](http://build.fhir.org/ig/HL7/bulk-data/export/index.html#response---complete-status) does not contain enough information to retry the request. Need to decide if this is a problem in practice and if so, how to remediate.

**Comment by cerbs** [comment]
FHIR supports using POSTing to <resource>/?_search for kicking off search requests, and the response bundle requires a self-link with the parameters used in the search. That self link could have the same or similar issues. I was trying to pull up the relevant links to in the FHIR spec thinking maybe it could offer some guidance but I'm not find anything that covers this directly.

[https://hl7.org/fhir/R4/http.html#search](https://hl7.org/fhir/R4/http.html#search)
> Because of the way that some user agents and proxies treat GET and POST requests, in addition to the get based search method above, servers that support search SHALL also support a POST based search:
> 
> POST  [base]/[type]/_search{?[parameters]{&_format=[mime-type]}}
> Content-Type: application/x-www-form-urlencoded
> 
> param1=value&param2=value
> 
> This has exactly the same semantics as the equivalent GET command. Note that in the POST variant, parameters may appear in both the URL and the body. Parameters have the same meaning in either place. Since parameters can repeat, putting them in both places is the same as repeating them (which is valid for some parameters and not for others).
> 
> Note: Supporting GET means that PHI (Personal health information) might appear in search parameters, and therefore in HTTP logs. For this reason logs should be regarded as being as sensitive as the resources themselves. This is a general requirement irrespective of the use of GET - see the security page for further commentary.
> 
> All these search interactions take a series of parameters that are a series of name=value pairs encoded in the URL (or as an application/x-www-form-urlencoded (Specification ) submission for a POST). (See W3C HTML forms ).
> 
>     Note: application/x-www-form-urlencoded is supported for POST so that invoking a search by GET or POST can be done from HTML forms in a browser (though considerable active content might be required in the browser), although this is not the main usage.
> 

And [https://hl7.org/fhir/R4/search.html#conformance](https://hl7.org/fhir/R4/search.html#conformance)
> 
>  In order to allow the client to be confident about what search parameters were used as criteria by the server, the server SHALL return the parameters that were actually used to process the search. Applications processing search results SHALL check these returned values where necessary. For example, if the server did not support some of the filters specified in the search, a client might manually apply those filters to the retrieved result set, display a warning message to the user or take some other action.
> 
> In the case of a RESTful search, these parameters are encoded in the self link in the bundle that is returned:
> 
>   <link>
>     <relation value="self"/>
>     <url value="http://example.org/Patient?name=peter"/>
>   </link>
> 

I think since the x-www-form-urlencoded header is formatted identically to the standard query parameter, the expectation is that if someone were to want to replay the query in a search response bundle, they grab the parameters from the self link and pass them in the x-www-form-urlencoded header.

**Comment by jmandel** [comment]
Mostly I've looked at the completion manifest's `request` field as a way for clients to know "have all the parameters I supplied been used/recognized by the server"? Is that right?

If so, we could focus on the list of parameters (rather than the list of values), so a client could directly tell if one of its params had been ignored/skipped.

**Comment by gotdan** [comment]
Resolved in #92
